# Generated by Django 5.1.5 on 2025-12-22 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('found_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='cases.foundperson')),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='cases.missingperson')),
            ],
        ),
    ]
