# Generated by Django 5.1.5 on 2025-12-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_matchsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsuggestion',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
