# Generated by Django 5.1.5 on 2025-12-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_matchsuggestion_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundperson',
            old_name='approx_age',
            new_name='approximate_age',
        ),
        migrations.RemoveField(
            model_name='foundperson',
            name='description',
        ),
        migrations.AddField(
            model_name='foundperson',
            name='clothing_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='distinctive_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='finder_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='finder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='finder_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='found_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='mental_state',
            field=models.CharField(blank=True, choices=[('ALERT', 'Alert/Normal'), ('CONFUSED', 'Confused'), ('DISTRESSED', 'Distressed'), ('UNCONSCIOUS', 'Unconscious'), ('INJURED', 'Injured')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='physical_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='identifying_marks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='clothing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
