# Generated by Django 4.2 on 2026-09-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_rename_approx_age_foundperson_approximate_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='last_seen_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
